### ISSUE TITLE
error

### ISSUE THREAD

**Issue by chl916185** [open-mmlab/mmeval#107]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\soft_files\anconda3\envs\mmseg\lib\site-packages\mmeval\__init__.py", line 7, in <module>
    from .metrics import *
  File "D:\soft_files\anconda3\envs\mmseg\lib\site-packages\mmeval\metrics\__init__.py", line 12, in <module>
    from .multi_label import AveragePrecision, MultiLabelMetric
  File "D:\soft_files\anconda3\envs\mmseg\lib\site-packages\mmeval\metrics\multi_label.py", line 171, in <module>
    class MultiLabelMetric(MultiLabelMixin, BaseMetric):
  File "D:\soft_files\anconda3\envs\mmseg\lib\site-packages\mmeval\metrics\multi_label.py", line 380, in MultiLabelMetric
    labels: Sequence['torch.Tensor']) -> List:
  File "D:\soft_files\anconda3\envs\mmseg\lib\site-packages\mmeval\core\dispatcher.py", line 236, in __call__
    signature._return_annotation)  # type: ignore
  File "D:\soft_files\anconda3\envs\mmseg\lib\site-packages\mmeval\core\dispatcher.py", line 218, in _traverse_type_hints
    for tp_arg in annotation.__args__:
TypeError: 'NoneType' object is not iterable

**Comment by zhouzaida** [comment]
Hi, this issue had been resolved by #77.
